#!/bin/bash

# Shared consensus-aware HiDe settings for Kaggle 2x T4 16GB.
if [ "${CONSENSUS_ENV_CONFIGURED:-0}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi
export CONSENSUS_ENV_CONFIGURED=1
CONSENSUS_SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONSENSUS_REPO_ROOT="$(cd -- "$CONSENSUS_SCRIPT_DIR/../../.." && pwd)"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export DEEPSPEED_INCLUDE="${DEEPSPEED_INCLUDE:-localhost:0,1}"
export TRAIN_LAUNCHER="${TRAIN_LAUNCHER:-deepspeed}"
export TRAIN_PER_DEVICE_BATCH="${TRAIN_PER_DEVICE_BATCH:-1}"
export TRAIN_PER_DEVICE_EVAL_BATCH="${TRAIN_PER_DEVICE_EVAL_BATCH:-1}"
export TRAIN_GRAD_ACCUM_STEPS="${TRAIN_GRAD_ACCUM_STEPS:-16}"
export TRAIN_MODEL_MAX_LENGTH="${TRAIN_MODEL_MAX_LENGTH:-768}"
export TRAIN_NUM_WORKERS="${TRAIN_NUM_WORKERS:-2}"
export TRAIN_BF16="${TRAIN_BF16:-False}"
export TRAIN_TF32="${TRAIN_TF32:-False}"
export TRAIN_SAVE_STRATEGY="${TRAIN_SAVE_STRATEGY:-epoch}"
export TRAIN_LOGGING_STEPS="${TRAIN_LOGGING_STEPS:-10}"
export UCIT_OUTPUT_ROOT="${UCIT_OUTPUT_ROOT:-$CONSENSUS_REPO_ROOT/outputs/ucit_consensus}"

export CONSENSUS_RANK="${CONSENSUS_RANK:-32}"
export CONSENSUS_RANK_SHARED="${CONSENSUS_RANK_SHARED:-32}"
export CONSENSUS_ETA="${CONSENSUS_ETA:-0.5}"
export CONSENSUS_NORMALIZE_FUSION="${CONSENSUS_NORMALIZE_FUSION:-True}"
export CONSENSUS_SAMPLE_LIMIT="${CONSENSUS_SAMPLE_LIMIT:-64}"
export CONSENSUS_SAMPLES_PER_FORWARD="${CONSENSUS_SAMPLES_PER_FORWARD:-2}"
export CONSENSUS_OVERSAMPLE="${CONSENSUS_OVERSAMPLE:-8}"

CONSENSUS_EXTRA_ARGS=(
  --bits 4
  --fp16 True
  --gradient_checkpointing True
  --consensus_enable True
  --consensus_rank "$CONSENSUS_RANK"
  --consensus_rank_shared "$CONSENSUS_RANK_SHARED"
  --consensus_eta "$CONSENSUS_ETA"
  --consensus_normalize_fusion "$CONSENSUS_NORMALIZE_FUSION"
  --consensus_sample_limit "$CONSENSUS_SAMPLE_LIMIT"
  --consensus_samples_per_forward "$CONSENSUS_SAMPLES_PER_FORWARD"
  --consensus_oversample "$CONSENSUS_OVERSAMPLE"
)

export EXTRA_TRAIN_ARGS="${CONSENSUS_EXTRA_ARGS[*]} ${EXTRA_TRAIN_ARGS:-}"
