#!/bin/bash

# Consensus-aware HiDe settings for one Modal A100 40GB GPU.
if [ "${MODAL_A100_CONSENSUS_ENV_CONFIGURED:-0}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi
export MODAL_A100_CONSENSUS_ENV_CONFIGURED=1

MODAL_A100_SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODAL_A100_REPO_ROOT="$(cd -- "$MODAL_A100_SCRIPT_DIR/../../.." && pwd)"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export TRAIN_LAUNCHER="${TRAIN_LAUNCHER:-python}"
export TRAIN_PER_DEVICE_BATCH="${TRAIN_PER_DEVICE_BATCH:-4}"
export TRAIN_PER_DEVICE_EVAL_BATCH="${TRAIN_PER_DEVICE_EVAL_BATCH:-1}"
export TRAIN_GRAD_ACCUM_STEPS="${TRAIN_GRAD_ACCUM_STEPS:-8}"
export TRAIN_MODEL_MAX_LENGTH="${TRAIN_MODEL_MAX_LENGTH:-1024}"
export TRAIN_NUM_WORKERS="${TRAIN_NUM_WORKERS:-4}"
export TRAIN_BF16="${TRAIN_BF16:-True}"
export TRAIN_TF32="${TRAIN_TF32:-True}"
export TRAIN_SAVE_STRATEGY="${TRAIN_SAVE_STRATEGY:-epoch}"
export TRAIN_SAVE_STEPS="${TRAIN_SAVE_STEPS:-100}"
export TRAIN_SAVE_TOTAL_LIMIT="${TRAIN_SAVE_TOTAL_LIMIT:-2}"
export TRAIN_RESUME_FROM_CHECKPOINT="${TRAIN_RESUME_FROM_CHECKPOINT:-}"
export TRAIN_LOGGING_STEPS="${TRAIN_LOGGING_STEPS:-10}"
export UCIT_OUTPUT_ROOT="${UCIT_OUTPUT_ROOT:-$MODAL_A100_REPO_ROOT/outputs/ucit_consensus_modal_a100}"

export CONSENSUS_RANK="${CONSENSUS_RANK:-32}"
export CONSENSUS_RANK_SHARED="${CONSENSUS_RANK_SHARED:-32}"
export CONSENSUS_ETA="${CONSENSUS_ETA:-0.5}"
export CONSENSUS_NORMALIZE_FUSION="${CONSENSUS_NORMALIZE_FUSION:-True}"
export CONSENSUS_SAMPLE_LIMIT="${CONSENSUS_SAMPLE_LIMIT:-128}"
export CONSENSUS_SAMPLES_PER_FORWARD="${CONSENSUS_SAMPLES_PER_FORWARD:-4}"
export CONSENSUS_OVERSAMPLE="${CONSENSUS_OVERSAMPLE:-8}"
export CONSENSUS_QUANT_MODE="${CONSENSUS_QUANT_MODE:-4bit}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:128}"

case "$CONSENSUS_QUANT_MODE" in
  4bit)
    MODAL_A100_QUANT_ARGS=(--bits 4)
    ;;
  bf16|16bit)
    MODAL_A100_QUANT_ARGS=(--bits 16)
    ;;
  *)
    echo "Unsupported CONSENSUS_QUANT_MODE='$CONSENSUS_QUANT_MODE'. Use 4bit or bf16."
    exit 1
    ;;
esac

MODAL_A100_CONSENSUS_EXTRA_ARGS=(
  "${MODAL_A100_QUANT_ARGS[@]}"
  --bf16 True
  --gradient_checkpointing True
  --consensus_enable True
  --consensus_rank "$CONSENSUS_RANK"
  --consensus_rank_shared "$CONSENSUS_RANK_SHARED"
  --consensus_eta "$CONSENSUS_ETA"
  --consensus_normalize_fusion "$CONSENSUS_NORMALIZE_FUSION"
  --consensus_sample_limit "$CONSENSUS_SAMPLE_LIMIT"
  --consensus_samples_per_forward "$CONSENSUS_SAMPLES_PER_FORWARD"
  --consensus_oversample "$CONSENSUS_OVERSAMPLE"
)

export EXTRA_TRAIN_ARGS="${MODAL_A100_CONSENSUS_EXTRA_ARGS[*]} ${EXTRA_TRAIN_ARGS:-}"
